database:
  host: localhost
  port: "3306"
  name: database
  user: user
  password: pass

events:
  "1":
    name: "Monster Hunt"
    active: true
    duration_days: 14
    max_progress: 12000
    description: "The realm is overrun with monsters! Join the Monster Hunt and track your progress as you defeat different creature types. Reach milestones to earn increasingly valuable rewards. Will you rise to become the ultimate monster slayer?"
    drop_chances:
      "0": 75
      "1": 10
      "2": 10
      "3": 3
      "5": 2

